name: Deploy UI to GitHub Pages

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Clean workspace (remove old repo directories)
        run: |
          rm -rf /home/runner/work/peashoot/peashoot
      - name: Set safe directory
        run: |
          /usr/bin/git config --global --add safe.directory /home/runner/work/mike-north/peashoot
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build @peashoot/ui (client)
        run: npx nx run @peashoot/ui:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/client/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
